dbPaths:
  base: data
  artists: data/artists.yaml
  songs:
    base: songs
    indexed: songs/indexed.yaml

server:
  address: :8080
  timeouts:
    shutdown: 10

startOptions:
  index: false

svelte:
  pages: ../yorubanashi.github.io/src/routes
